import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { StatusBadge } from "../../components/StatusBadge";
import { TonerBar } from "../../components/TonerBar";
import { formatDateTime, formatNumber } from "../../lib/format";
export function PrinterCard({ printer, isBusy, onEdit, onPoll }) {
    const model = printer.lastSeenModel ?? printer.model ?? "Unknown model";
    const tonerPreview = printer.latestToners.slice(0, 4);
    return (_jsxs("article", { className: "panel bg-lattice p-5", children: [_jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Link, { to: `/printers/${printer.id}`, className: "text-xl font-semibold text-ink hover:text-accent", children: printer.name }), _jsx(StatusBadge, { state: printer.lastAvailability })] }), _jsxs("div", { className: "mt-2 flex flex-wrap gap-2 text-sm text-slate-600", children: [_jsx("span", { children: printer.ipAddress }), _jsx("span", { className: "text-line", children: "\u2022" }), _jsx("span", { children: model }), printer.location ? (_jsxs(_Fragment, { children: [_jsx("span", { className: "text-line", children: "\u2022" }), _jsx("span", { children: printer.location })] })) : null] })] }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { type: "button", className: "button-secondary px-3 py-2", onClick: () => onEdit(printer), children: "Upravit" }), _jsx("button", { type: "button", className: "button-primary px-3 py-2", onClick: () => onPoll(printer), disabled: isBusy, children: isBusy ? "Polluji..." : "Poll" })] })] }), _jsxs("div", { className: "mt-5 grid gap-4 md:grid-cols-2", children: [_jsxs("div", { className: "rounded-2xl border border-line/80 bg-white/85 p-4", children: [_jsx("div", { className: "text-xs font-semibold uppercase tracking-[0.18em] text-slate-500", children: "Page counter" }), _jsx("div", { className: "mt-2 text-2xl font-semibold text-ink", children: formatNumber(printer.lastPageCounter) }), _jsxs("div", { className: "mt-3 text-sm text-slate-600", children: ["Posledn\u00ED aktualizace: ", formatDateTime(printer.lastPolledAt)] })] }), _jsxs("div", { className: "rounded-2xl border border-line/80 bg-white/85 p-4", children: [_jsx("div", { className: "text-xs font-semibold uppercase tracking-[0.18em] text-slate-500", children: "Stav za\u0159\u00EDzen\u00ED" }), _jsx("div", { className: "mt-2 text-lg font-semibold text-ink", children: printer.lastDeviceStatus ?? "Unknown" }), _jsxs("div", { className: "mt-3 text-sm text-slate-600", children: ["Posledn\u00ED \u00FAsp\u011B\u0161n\u00FD kontakt: ", formatDateTime(printer.lastSuccessfulAt)] })] })] }), _jsx("div", { className: "mt-5 grid gap-3", children: tonerPreview.length > 0 ? (tonerPreview.map((toner) => _jsx(TonerBar, { toner: toner }, toner.key))) : (_jsx("div", { className: "rounded-2xl border border-dashed border-line bg-white/70 p-4 text-sm text-slate-500", children: "Toner data zat\u00EDm nejsou dostupn\u00E1." })) })] }));
}
